build: bump to lnd v0.17.0-beta.rc1
lightninglabs/lndinit pull request #35
Opened 2023-08-29 20:13 UTC by calvinrzachman

2023-08-29 20:18 UTC, guggero commented
We need to add the `replace` to all our products now, unfortunately:
https://github.com/lightningnetwork/lnd/blob/master/go.mod#L207

2023-08-30 08:05 UTC, guggero approved these changes
LGTM :tada:

2023-08-31 19:35 UTC, Roasbeef requested changes

2023-08-31 19:35 UTC, Roasbeef commented on Dockerfile
> +ARG BASE_IMAGE_VERSION=v0.17.0-beta.rc1
rc2?

2023-08-31 22:13 UTC, merged