README: fix `init-wallet` cmd
lightninglabs/lndinit pull request #8
Opened 2022-03-31 08:59 UTC by erikarvstedt

2022-03-31 10:41 UTC, guggero requested changes
Thanks for the fix!

2022-03-31 10:41 UTC, guggero commented on README.md
> -    --secret-source=file \
I'd like to keep the examples as explicit as possible, so please leave this in, even though it's the default.

2022-03-31 10:41 UTC, guggero commented on README.md
> +    --init-file.output-wallet-dir=$HOME/.lnd/data/chain/bitcoin/mainnet \
Nice catch!

2022-03-31 10:47 UTC, guggero approved these changes
LGTM :tada:

2022-04-04 19:57 UTC, thinkmassive approved these changes
nice, thank you @erikarvstedt!

2022-04-04 20:37 UTC, merged